title = "Hugo Netlify Starter"
disableKinds = ["taxonomy", "taxonomyTerm"]
copyright = "Cloud Native Computing Foundation"

enableGitInfo = true

[markup.highlight]
style = "paraiso-dark"

[params]
font_awesome_version = "5.12.0"
description = "Boilerplate for building beautiful websites"
favicon = "favicon.png"
repositoryUrl = "https://github.com/cncf/hugo-netlify-starter"
contentDir = "/content/"

[params.logos]
navbar = "cncf-color.png"

[[params.social]]
name = "Twitter"
color = "#00aced"
url = "https://twitter.com/CloudNativeFdn"
icon = "fab fa-twitter"

[[params.fonts]]
name = "Open Sans"
sizes = [300, 400, 600, 700]
type = "sans_serif"

[[params.fonts]]
name = "Fira Mono"
sizes = [300, 400, 600, 700]
type = "monospace"

[[params.fonts]]
name = "Open Sans"
sizes = [100, 200, 300, 400, 500, 600, 700]
type = "heading_font"

[[menu.main]]
name = "About"
url = "/"
weight = 1

[[menu.main]]
name = "General guidance"
url = "/general-guidance"
weight = 2

[[menu.main]]
name = "Word replacement list"
url = "/word-list"
weight = 3

[[menu.main]]
name = "Supporting organizations"
url = "/organizations"
weight = 4

[[menu.main]]
name = "Supporting organizations"
url = "/organizations"
weight = 4
