title = "Inclusive Language Project"
disableKinds = ["taxonomy", "taxonomyTerm"]
#copyright = "The project authors"

enableGitInfo = true

[markup.highlight]
style = "paraiso-dark"

[params]
font_awesome_version = "5.12.0"
description = "A project for inclusive language and terminology in open source and technology"
favicon = ""
repositoryUrl = "https://github.com/cncf/hugo-netlify-starter"
contentDir = "/content/"

[params.logos]
navbar = "inclusive-naming-logo.svg"

[[params.social]]
name = "Twitter"
url = "https://twitter.com/inclusivenaming"
icon = "fab fa-twitter"

[[params.social]]
name = "GitHub"
url = "https://github.com/inclusivenaming"
icon = "fab fa-github"

[[params.social]]
name = "Mailing list"
url = "https://groups.google.com/g/inclusivenaming"
icon = "fas fa-envelope"

[[params.fonts]]
name = "Open Sans"
sizes = [300, 400, 600, 700, 900]
type = "sans_serif"

# [[params.fonts]]
# name = "Fira Mono"
# sizes = [300, 400, 600, 700]
# type = "monospace"

[[params.fonts]]
name = "Lexend Deca"
sizes = [400]
type = "heading_font"

# [[menu.main]]
# name = "About"
# url = "/"
# weight = 1

# [[menu.main]]
# name = "General guidance"
# url = "/general-guidance"
# weight = 2

# [[menu.main]]
# name = "Related projects"
# url = "/related-projects"
# weight = 3

[[menu.main]]
name = "Word replacement list"
url = "/word-list"
weight = 3

# [[menu.main]]
# name = "Supporting organizations"
# url = "/organizations"
# weight = 4
